### ISSUE TITLE
Label tabs to match the open Registry or Docker instance

### ISSUE THREAD

**Issue by slimbrd** [CaptiveAire/DockerPowerTools#1]

**Comment by slimbrd** [comment]
Example:

![image](https://user-images.githubusercontent.com/20357194/45819724-0c84d580-bcb3-11e8-8ca7-d1d5f64c9a0e.png)

**Comment by rquackenbush** [comment]
First part is done. The title is now formatted as "Registry - <registryname>". Need to look more into the second part.

**Comment by rquackenbush** [comment]
Second part done. The title (same format) now shows up on floating document view.
